### PR TITLE
Zombies Slow on attack

### PR DESCRIPTION
**Pull request by AntonAsbrink**
The zombies slows the player when landing an attack.
I rebalanced the enemies a bit to compensate for this buff.

### CODE REVIEW

**Review by fjz345 — DISMISSED** [review]
Need to merge with develop

**Review by fredrix96 — DISMISSED** [review]
Works smoothly, nice! Maybe we should consider a visual effect in the future

**Review by fjz345 — DISMISSED** [review]
Slow does not get updated until you do an input

**Review by fredrix96 — DISMISSED** [review]

**Review by fjz345 — APPROVED** [review]
Bra

**Review by fredrix96 — APPROVED** [review]

**Pull request merged**
