### PR TITLE
ID:64 AddDynamic Entity

### PR DESCRIPTION
**Pull request by fjz345**
Important note: you have to make sure yourself that the model has been loaded if you add it to the scene.

The plan is that for example: ArrowShots
You in the scene/or straight in main call AssetLoader()->Load() on everything the arrow needs.

Then you just create new entity.

### CODE REVIEW

**Review by Schtekt — DISMISSED** [review]
Not much to say. No problems found.

**Review by jocke1995 — CHANGES_REQUESTED** [review]
Remove tests from main, then you're good to go

**Review by jocke1995 — DISMISSED** [review]
You should've made a new bransch.

**Review by jocke1995 — APPROVED** [review]
Seems to work, finally

**Review by Schtekt — APPROVED** [review]

**Pull request merged**
