### PR TITLE
Smooth movement

### PR DESCRIPTION
**Pull request by Schtekt**
The player now "hovers" above the ground.
This changes how the player moves, affecting ALL entities using the playerinputcomponent.
A known issue is that regular shapes (boxes and spheres) fall through flat surfaces. We found this acceptable as these shapes are not to represent the player character any longer.

### CODE REVIEW

**Review by jakkeez — COMMENTED** [review]
Currently experiencing problems with "Smooth Movement". After conditions are met (Tim knows that I am talking about), the player model falls right through the floor.

**Comment by Schtekt** [comment]
The last error was caused by gravity being applied several times, as it was never "hitting" the ground the bt velocity automatically updated in the bullet physics black box.

Should work fine now 🥇

**Review by LeoWikstrom — DISMISSED** [review]
Works well 👍

**Review by jakkeez — CHANGES_REQUESTED** [review]
Sometimes when running the gravity goes bonkers and makes the player fly away.

**Comment by Schtekt** [comment]
Gravity will now always kick in when player jumps, my bad!

**Review by jakkeez — APPROVED** [review]

**Review by LeoWikstrom — APPROVED** [review]

**Pull request merged**
