### PR TITLE
HDR

### PR DESCRIPTION
**Pull request by jocke1995**

### CODE REVIEW

**Review by fredrix96 — DISMISSED** [review]
Looks good! Nice function in main.cpp

**Review by OtakuFreak13 — DISMISSED** [review]
From what I can see it looks okay. Funky colours in test scene.

**Review by OtakuFreak13 — APPROVED** [review]
I aprove of this merge.

**Review by fredrix96 — APPROVED** [review]
I can not find anything bad. Well done, again!

**Pull request merged**
